name: ers-transit
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - git
  - matplotlib
  - numpy
  - scipy
  - astropy
  - bokeh
  - h5py
  - pandas
  - pytest
  - pyyaml
  - requests
  - nbsphinx
  - tqdm
  - lmfit
  - batman-package
  - pip
  - pip:
      - svo-filters
      # eureka-hack (does not exist yet!)
